lib: [
  "_build/install/default/lib/async_read/META"
  "_build/install/default/lib/async_read/async_read.a"
  "_build/install/default/lib/async_read/async_read.cma"
  "_build/install/default/lib/async_read/async_read.cmi"
  "_build/install/default/lib/async_read/async_read.cmt"
  "_build/install/default/lib/async_read/async_read.cmx"
  "_build/install/default/lib/async_read/async_read.cmxa"
  "_build/install/default/lib/async_read/async_read.ml"
  "_build/install/default/lib/async_read/dune-package"
  "_build/install/default/lib/async_read/opam"
]
libexec: [
  "_build/install/default/lib/async_read/async_read.cmxs"
]
bin: [
  "_build/install/default/bin/async_read"
]
